model:
  base_learning_rate: 4.5e-6
  target: taming.models.autoae.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target: taming.modules.losses.vqperceptual.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.0001
        disc_weight: 0.5
    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0



data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /raid/datasets/touch2vision/gel_kl_train.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /raid/datasets/touch2vision/gel_kl_test.txt
        size: 256

